published: true
slug: mezmo-changelog
description: "Release notes for Mezmo's Telemetry Pipeline and Log Analysis products."
collapsed: true
collapsedCategories: true
showLastUpdated: false
showLastUpdateUser: false
locale: en_us
